"""
Report Generator - PDF Reports using ReportLab
"""

import os
import re
from datetime import datetime
from typing import Dict, List
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT


class ReportGenerator:
    def __init__(self, results_folder: str):
        self.results_folder = results_folder
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a1a1a'),
            spaceAfter=30,
            alignment=TA_CENTER
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2c3e50'),
            spaceAfter=12,
            spaceBefore=12
        ))
        
        self.styles.add(ParagraphStyle(
            name='Finding',
            parent=self.styles['Normal'],
            fontSize=10,
            leftIndent=20,
            spaceAfter=6
        ))
    
    def _ensure_target_folder(self, target: str) -> str:
        """Create target-specific results folder"""
        safe_target = re.sub(r'[^\w\-.]', '_', target)
        target_path = os.path.join(self.results_folder, safe_target)
        os.makedirs(target_path, exist_ok=True)
        return target_path
    
    def _read_result_file(self, filepath: str) -> str:
        """Read content from result file"""
        try:
            if os.path.exists(filepath):
                with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                    return f.read()
            return "No data available"
        except:
            return "Error reading file"
    
    def _sanitize_text(self, text: str) -> str:
        """Sanitize text for PDF"""
        # Replace special characters that might cause issues
        text = text.replace('&', '&amp;')
        text = text.replace('<', '&lt;')
        text = text.replace('>', '&gt;')
        return text
    
    def generate_report(self, target: str, scan_data: Dict[str, any]) -> Dict[str, str]:
        """Generate comprehensive PDF report"""
        try:
            target_path = self._ensure_target_folder(target)
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            pdf_filename = f"security_report_{timestamp}.pdf"
            pdf_path = os.path.join(target_path, pdf_filename)
            
            # Create PDF document
            doc = SimpleDocTemplate(pdf_path, pagesize=letter,
                                   rightMargin=72, leftMargin=72,
                                   topMargin=72, bottomMargin=18)
            
            # Container for PDF elements
            story = []
            
            # Title Page
            story.append(Spacer(1, 2*inch))
            title = Paragraph("Security Assessment Report", self.styles['CustomTitle'])
            story.append(title)
            story.append(Spacer(1, 0.5*inch))
            
            # Target info
            info_data = [
                ['Target:', target],
                ['Report Date:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
                ['Generated By:', 'NeoxSecBot']
            ]
            info_table = Table(info_data, colWidths=[2*inch, 4*inch])
            info_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 12),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ]))
            story.append(info_table)
            story.append(PageBreak())
            
            # Executive Summary
            story.append(Paragraph("Executive Summary", self.styles['SectionHeader']))
            summary_text = f"""
            This report contains the results of a security assessment performed on {target}.
            The assessment included reconnaissance, vulnerability scanning, directory enumeration,
            and login security testing. All findings are documented below.
            """
            story.append(Paragraph(summary_text, self.styles['Normal']))
            story.append(Spacer(1, 0.3*inch))
            
            # Findings Summary Table
            findings_data = [
                ['Category', 'Status', 'Issues Found'],
                ['Reconnaissance', scan_data.get('recon_status', 'N/A'), 
                 str(scan_data.get('recon_findings', 0))],
                ['Web Vulnerabilities', scan_data.get('webscan_status', 'N/A'), 
                 str(scan_data.get('webscan_findings', 0))],
                ['Directory Enumeration', scan_data.get('dir_status', 'N/A'), 
                 str(scan_data.get('dir_findings', 0))],
                ['Login Security', scan_data.get('login_status', 'N/A'), 
                 str(scan_data.get('login_findings', 0))],
            ]
            
            findings_table = Table(findings_data, colWidths=[2.5*inch, 1.5*inch, 1.5*inch])
            findings_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            story.append(findings_table)
            story.append(PageBreak())
            
            # Detailed Findings
            story.append(Paragraph("Detailed Findings", self.styles['SectionHeader']))
            
            # Reconnaissance Results
            if scan_data.get('recon_data'):
                story.append(Paragraph("1. Reconnaissance", self.styles['Heading3']))
                recon_text = self._sanitize_text(scan_data['recon_data'][:2000])  # Limit length
                story.append(Paragraph(f"<pre>{recon_text}</pre>", self.styles['Code']))
                story.append(Spacer(1, 0.2*inch))
            
            # Web Scan Results
            if scan_data.get('webscan_data'):
                story.append(Paragraph("2. Web Vulnerability Scan", self.styles['Heading3']))
                webscan_text = self._sanitize_text(scan_data['webscan_data'][:2000])
                story.append(Paragraph(f"<pre>{webscan_text}</pre>", self.styles['Code']))
                story.append(Spacer(1, 0.2*inch))
            
            # Directory Scan Results
            if scan_data.get('dir_data'):
                story.append(Paragraph("3. Directory Enumeration", self.styles['Heading3']))
                dir_text = self._sanitize_text(scan_data['dir_data'][:2000])
                story.append(Paragraph(f"<pre>{dir_text}</pre>", self.styles['Code']))
                story.append(Spacer(1, 0.2*inch))
            
            # Login Check Results
            if scan_data.get('login_data'):
                story.append(Paragraph("4. Login Security Analysis", self.styles['Heading3']))
                login_text = self._sanitize_text(scan_data['login_data'][:2000])
                story.append(Paragraph(f"<pre>{login_text}</pre>", self.styles['Code']))
                story.append(Spacer(1, 0.2*inch))
            
            # Recommendations
            story.append(PageBreak())
            story.append(Paragraph("Recommendations", self.styles['SectionHeader']))
            
            recommendations = [
                "1. Implement all missing security headers (HSTS, CSP, X-Frame-Options, etc.)",
                "2. Ensure all cookies have Secure, HttpOnly, and SameSite flags set",
                "3. Implement CSRF protection on all forms",
                "4. Add rate limiting to prevent brute force attacks",
                "5. Remove or secure any exposed sensitive files and directories",
                "6. Keep all software and frameworks up to date",
                "7. Implement proper input validation and output encoding",
                "8. Use strong password policies and multi-factor authentication",
                "9. Regular security audits and penetration testing",
                "10. Monitor logs for suspicious activity"
            ]
            
            for rec in recommendations:
                story.append(Paragraph(rec, self.styles['Finding']))
                story.append(Spacer(1, 0.1*inch))
            
            # Disclaimer
            story.append(PageBreak())
            story.append(Paragraph("Disclaimer", self.styles['SectionHeader']))
            disclaimer = """
            This report is provided for educational and authorized security testing purposes only.
            The findings in this report should be verified manually. The tool and its operators
            are not responsible for any misuse of this information. Always obtain proper
            authorization before conducting security assessments.
            """
            story.append(Paragraph(disclaimer, self.styles['Normal']))
            
            # Build PDF
            doc.build(story)
            
            return {
                'status': 'success',
                'file': pdf_path,
                'message': f'Report generated: {pdf_filename}'
            }
        except Exception as e:
            return {
                'status': 'error',
                'message': f'Error generating report: {str(e)}'
            }
    
    def generate_simple_report(self, target: str, results_text: str) -> Dict[str, str]:
        """Generate simple text-based report"""
        try:
            target_path = self._ensure_target_folder(target)
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            report_filename = f"report_{timestamp}.txt"
            report_path = os.path.join(target_path, report_filename)
            
            with open(report_path, 'w', encoding='utf-8') as f:
                f.write("="*80 + "\n")
                f.write("SECURITY ASSESSMENT REPORT\n")
                f.write("="*80 + "\n\n")
                f.write(f"Target: {target}\n")
                f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"Generated by: NeoxSecBot\n")
                f.write("="*80 + "\n\n")
                f.write(results_text)
                f.write("\n\n" + "="*80 + "\n")
                f.write("END OF REPORT\n")
                f.write("="*80 + "\n")
            
            return {
                'status': 'success',
                'file': report_path,
                'message': f'Text report generated: {report_filename}'
            }
        except Exception as e:
            return {
                'status': 'error',
                'message': f'Error generating text report: {str(e)}'
            }


# Export functions
async def generate_pdf_report(target: str, results_folder: str, 
                             scan_data: Dict[str, any]) -> Dict[str, str]:
    generator = ReportGenerator(results_folder)
    return generator.generate_report(target, scan_data)

async def generate_text_report(target: str, results_folder: str, 
                              results_text: str) -> Dict[str, str]:
    generator = ReportGenerator(results_folder)
    return generator.generate_simple_report(target, results_text)
